-- Buzzent StockPilot: esquema multiempresa seguro.
create extension if not exists pgcrypto;
create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text, created_at timestamptz not null default now());
create table if not exists public.businesses (id uuid primary key default gen_random_uuid(), name text not null, currency text not null default 'ARS', timezone text not null default 'America/Argentina/Buenos_Aires', created_at timestamptz not null default now());
create table if not exists public.business_members (business_id uuid references public.businesses(id) on delete cascade, user_id uuid references auth.users(id) on delete cascade, role text not null default 'member' check (role in ('owner','admin','member')), created_at timestamptz not null default now(), primary key(business_id,user_id));
create table if not exists public.categories (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, name text not null, unique(business_id,name));
create table if not exists public.products (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, category_id uuid references public.categories(id) on delete set null, name text not null, description text, sku text not null, barcode text, cost numeric(12,2) not null default 0 check(cost >= 0), price numeric(12,2) check(price is null or price >= 0), stock integer not null default 0 check(stock >= 0), minimum_stock integer not null default 0 check(minimum_stock >= 0), unit text not null default 'unidad', image_path text, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(business_id,sku));
create table if not exists public.inventory_movements (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, product_id uuid not null references public.products(id) on delete restrict, type text not null check(type in ('Entrada','Salida','Ajuste','Pérdida')), quantity integer not null check(quantity > 0), reason text not null default '', reference text, user_id uuid not null references auth.users(id), created_at timestamptz not null default now());
create table if not exists public.notification_preferences (business_id uuid primary key references public.businesses(id) on delete cascade, user_id uuid not null references auth.users(id), low_stock boolean not null default true, push_enabled boolean not null default false, updated_at timestamptz not null default now());
create or replace function public.is_business_member(target uuid) returns boolean language sql security definer set search_path=public as $$ select exists(select 1 from business_members where business_id=target and user_id=auth.uid()); $$;
alter table public.profiles enable row level security; alter table public.businesses enable row level security; alter table public.business_members enable row level security; alter table public.categories enable row level security; alter table public.products enable row level security; alter table public.inventory_movements enable row level security; alter table public.notification_preferences enable row level security;
create policy profiles_self on public.profiles for all using (id=auth.uid()) with check (id=auth.uid());
create policy businesses_member on public.businesses for select using (public.is_business_member(id));
create policy members_same_business on public.business_members for select using (user_id=auth.uid() or public.is_business_member(business_id));
create policy categories_member on public.categories for all using (public.is_business_member(business_id)) with check (public.is_business_member(business_id));
create policy products_member on public.products for all using (public.is_business_member(business_id)) with check (public.is_business_member(business_id));
create policy movements_member on public.inventory_movements for all using (public.is_business_member(business_id)) with check (public.is_business_member(business_id) and user_id=auth.uid());
create policy notification_member on public.notification_preferences for all using (public.is_business_member(business_id) and user_id=auth.uid()) with check (public.is_business_member(business_id) and user_id=auth.uid());
create or replace function public.record_inventory_movement(p_business uuid,p_product uuid,p_type text,p_quantity integer,p_reason text default '',p_reference text default '') returns public.inventory_movements language plpgsql security invoker set search_path=public as $$ declare current_stock integer; result public.inventory_movements; delta integer; begin if not public.is_business_member(p_business) then raise exception 'not authorized'; end if; if p_quantity <= 0 then raise exception 'quantity must be positive'; end if; if p_type not in ('Entrada','Salida','Ajuste','Pérdida') then raise exception 'invalid movement type'; end if; select stock into current_stock from products where id=p_product and business_id=p_business for update; if current_stock is null then raise exception 'product not found'; end if; delta := case when p_type='Entrada' then p_quantity else -p_quantity end; if current_stock + delta < 0 then raise exception 'stock cannot be negative'; end if; update products set stock=stock+delta, updated_at=now() where id=p_product and business_id=p_business; insert into inventory_movements(business_id,product_id,type,quantity,reason,reference,user_id) values(p_business,p_product,p_type,p_quantity,p_reason,p_reference,auth.uid()) returning * into result; return result; end; $$;
